[[CURRENCIES]]
code="StellarEU"
issuer="GALN76JFY2ROUGZB2P4YRYFAHZTBUF4ZKSJ7ENUTG7CJNFFUNG6KYFUL"
display_decimals=7
name="StellarEU Token"
desc="Token was made by Elton Aldreiks Value Developer . StellarEU is an utility token to store and move value with almost no fee for the secure and fast transaction. StellarEU is a token of the blockchain stellar.org and can be bought with the native cryptocurrency XLM in the exchange of the Stellar Development Fondation "
